- platform: group
  name: Motion sensors
  unique_id: motion_sensors
  entities:
    - binary_sensor.family_room_motion
    - binary_sensor.hall_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.loft_motion
    - binary_sensor.living_room_motion
    - binary_sensor.garage_motion
    - binary_sensor.master_bath_motion
    - binary_sensor.water_closet_motion
    - binary_sensor.guest_bath_motion

- platform: group
  name: Garage_motion
  unique_id: garage_motion
  entities:
    - binary_sensor.garage_motion_1
    - binary_sensor.garage_motion_2
    - binary_sensor.garage_motion_3

- platform: group
  name: Hall motion
  unique_id: hall_motion
  entities:
    - binary_sensor.hall_motion_1
    - binary_sensor.hall_motion_2

- platform: group
  name: Living room motion
  unique_id: living_room_motion
  entities:
    - binary_sensor.living_room_motion_1
    - binary_sensor.living_room_motion_2
